import type { Metadata } from 'next';
import CssBaseline from '@mui/material/CssBaseline';
import './globals.css';
import { AuthContextProvider } from '@/contexts/authContext';
// import ThemeRegistry from '../ultils/themeRegistry';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/ultils/theme';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { kanit, teko } from '@/ultils/fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthContextProvider>
			<html lang="en">
				<body className={`${kanit.className} ${teko.className}`}>
					<CssBaseline />
					<ThemeProvider
						theme={theme}
					>
						{children}
					</ThemeProvider>
					{/* <ToastContainer /> */}
				</body>

			</html>
		</AuthContextProvider>
	);
}
