import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/contexts/authContext';
// import ThemeRegistry from '../ultils/themeRegistry';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/ultils/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthContextProvider>
			<html lang="en">
				<body className={inter.className}>
					<ThemeProvider
						theme={theme}
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</AuthContextProvider>
	);
}
